#! /bin/bash
# this script creates a C++ project including:
# - *.cpp (main file) 
# - *.hpp (header file)
# - *.cpp (implementation file for .hpp)
#
#############################################################################
#
# usage: run the script with a naming convention
#        
# example: ./run_script project_name
#  
# post-script: you should have the following in your directory... 
#
# example:  project_name.cpp  
# 	    project_name.hpp 
# 	    main.cpp
#
##############################################################################



##############################################################################
#####                 This creates the header file                 ###########
##############################################################################
echo "//Author: " > $1.hpp
echo "//Date: "$(date) >> $1.hpp
echo "//Sources: " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo "#include<iostream>" >> $1.hpp
echo "#include<string>" >> $1.hpp
echo "#include<math>" >> $1.hpp
echo "#include<fstream>" >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo "#ifndef "${1^^}"_H_INCLUDED" >> $1.hpp
echo "#define "${1^^}"_H_INCLUDED" >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo " " >> $1.hpp
echo "#endif" >> $1.hpp




##############################################################################
######     This creates the implementation file for the .hpp file      #########
##############################################################################
echo "//Author: " > $1.cpp
echo "//Date: "$(date) >> $1.cpp
echo "//Sources: " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo "#include ""\"$1.hpp\"" >> $1.cpp




##############################################################################
######      This creates the main file for the project            ##########
##############################################################################
echo "//Author: " > main.cpp
echo "//Date: "$(date) >> main.cpp
echo "//Sources: " >> main.cpp 
echo " " >> main.cpp
echo " " >> main.cpp
echo " " >> main.cpp
echo " " >> main.cpp
echo " " >> main.cpp
echo "#include ""\"$1.hpp\"" >> main.cpp
echo " " >> main.cpp
echo " " >> main.cpp
echo "int main()" >> main.cpp
echo "{" >> main.cpp
echo " " >> main.cpp
echo " " >> main.cpp
echo "    return 0;" >> main.cpp
echo "}" >> main.cpp
