#! /bin/bash
# this script creates a C++ project including:
# - *.cpp (driver file) 
# - *.h (header file)
# - *.cpp (implementation file for .h)
#
#############################################################################
#
# usage: run the script with a naming convention
#        
# example: ./run_script project_name
#  
# post-script: you should have the following in your directory... 
#
# example:  project_name.cpp  
# 	    project_name.h 
# 	    driver.cpp
#
##############################################################################



##############################################################################
#####                 This creates the header file                 ###########
##############################################################################
echo "//Author: " > $1.h
echo "//Date: "$(date) >> $1.h
echo "//Sources: " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo "#include<iostream>" >> $1.h
echo "#include<string>" >> $1.h
echo "#include<math>" >> $1.h
echo "#include<fstream>" >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo "#ifndef "${1^^}"_H_INCLUDED" >> $1.h
echo "#define "${1^^}"_H_INCLUDED" >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo " " >> $1.h
echo "#endif" >> $1.h




##############################################################################
######     This creates the implementation file for the .h file      #########
##############################################################################
echo "//Author: " > $1.cpp
echo "//Date: "$(date) >> $1.cpp
echo "//Sources: " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo " " >> $1.cpp
echo "#include ""\"$1.h\"" >> $1.cpp




##############################################################################
######      This creates the driver file for the project            ##########
##############################################################################
echo "//Author: " > driver.cpp
echo "//Date: "$(date) >> driver.cpp
echo "//Sources: " >> driver.cpp 
echo " " >> driver.cpp
echo " " >> driver.cpp
echo " " >> driver.cpp
echo " " >> driver.cpp
echo " " >> driver.cpp
echo "#include ""\"$1.h\"" >> driver.cpp
echo " " >> driver.cpp
echo " " >> driver.cpp
echo "int main()" >> driver.cpp
echo "{" >> driver.cpp
echo " " >> driver.cpp
echo " " >> driver.cpp
echo "    return 0;" >> driver.cpp
echo "}" >> driver.cpp
